# Generated by Django 4.0.6 on 2022-09-26 12:44

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizopenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(blank=True, max_length=1055, null=True)),
                ('price_name', models.CharField(blank=True, max_length=1055, null=True)),
                ('quiz_numbers', models.IntegerField(blank=True, null=True)),
                ('quiz_payment', models.IntegerField(blank=True, default='1', null=True)),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('duation_time', models.DurationField(blank=True, default=datetime.timedelta(seconds=1800), null=True)),
                ('status', models.CharField(choices=[('CLOSED', 'CLOSED'), ('CANCELLED', 'CANCELLED'), ('OPENED', 'OPENED')], default='OPENED', max_length=100)),
                ('send_email_request', models.BooleanField(default=False)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-creation'],
            },
        ),
    ]
