# Generated by Django 4.0.6 on 2022-09-26 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizopen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizstartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_game_status', models.CharField(blank=True, choices=[('PLAYED', 'PLAYED'), ('UNPLAYED', 'UNPLAYED')], default='UNPLAYED', max_length=1055, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], default='UNPAID', max_length=1055, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=1055, null=True)),
                ('payment_link_generated', models.CharField(blank=True, max_length=1055, null=True)),
                ('user_quiz_start_time', models.DateTimeField(blank=True, null=True)),
                ('user_quiz_end_time', models.DateTimeField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=1055, null=True)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('quizopen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizopen.quizopenmodel')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
