# Generated by Django 4.1 on 2025-03-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizUINModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UIN', models.CharField(max_length=20, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('updation', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
