# Generated by Django 4.0.6 on 2022-09-26 12:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1055, null=True)),
                ('meta_title', models.CharField(blank=True, default='title', max_length=1055, null=True)),
                ('meta_description', models.CharField(blank=True, default='description', max_length=1055, null=True)),
                ('msg', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('pic', models.ImageField(upload_to='blog/')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
