# Generated by Django 4.0.6 on 2022-09-26 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assigned_quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizattemptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.CharField(blank=True, max_length=1055, null=True)),
                ('compared_answer', models.CharField(blank=True, max_length=1055, null=True)),
                ('status', models.CharField(blank=True, choices=[('SKIPPED', 'SKIPPED'), ('SUBMITTED', 'SUBMITTED')], max_length=1055, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=1055, null=True)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('assignedquiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assigned_quiz.assignedquizmodel')),
            ],
        ),
    ]
