# Generated by Django 4.0.6 on 2022-12-01 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyDataDisplayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_users', models.CharField(blank=True, max_length=1055, null=True)),
                ('user_satisfaction_rate', models.CharField(blank=True, max_length=1055, null=True)),
                ('user_groth_rate', models.CharField(blank=True, max_length=1055, null=True)),
                ('next_segment', models.CharField(blank=True, max_length=1055, null=True)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
