# Generated by Django 4.0.6 on 2022-12-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dummydatadisplaymodel',
            old_name='user_groth_rate',
            new_name='user_growth_rate',
        ),
    ]
