# Generated by Django 4.0.6 on 2022-12-12 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_groth_rate_dummydatadisplaymodel_user_growth_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmailAllUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(blank=True, max_length=1055, null=True)),
                ('end', models.CharField(blank=True, max_length=1055, null=True)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='SendEmailAllUserPaidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(blank=True, max_length=1055, null=True)),
                ('end', models.CharField(blank=True, max_length=1055, null=True)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
