# Generated by Django 4.0.6 on 2022-09-26 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizopen', '0001_initial'),
        ('quizresult', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizwinnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('quizopen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizopen.quizopenmodel')),
                ('quizresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizresult.quizresultmodel')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizwinnerAnnoucementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('quizopen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizopen.quizopenmodel')),
            ],
        ),
    ]
