# Generated by Django 4.0.6 on 2022-09-26 12:44

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1055, null=True)),
                ('email', models.CharField(blank=True, max_length=1055, null=True)),
                ('phone', models.CharField(blank=True, max_length=1055, null=True)),
                ('subject', models.CharField(blank=True, max_length=1055, null=True)),
                ('message', models.CharField(blank=True, max_length=1055, null=True)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=1055, null=True)),
                ('option_one', models.CharField(blank=True, max_length=1055, null=True)),
                ('option_two', models.CharField(blank=True, max_length=1055, null=True)),
                ('option_three', models.CharField(blank=True, max_length=1055, null=True)),
                ('option_four', models.CharField(blank=True, max_length=1055, null=True)),
                ('option_correct', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=6)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
