# Generated by Django 4.0.6 on 2022-09-26 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizopen', '0001_initial'),
        ('qestions', '0001_initial'),
        ('quizstart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedquizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(blank=True, max_length=1055, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=1055, null=True)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qestions.questionmodel')),
                ('quizopen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizopen.quizopenmodel')),
                ('quizstart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizstart.quizstartmodel')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
