# Generated by Django 4.0.6 on 2022-09-26 12:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizopen', '0001_initial'),
        ('quizstart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizresultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_time_duration', models.CharField(blank=True, max_length=1055, null=True)),
                ('user_time_duration_actual', models.DurationField(blank=True, default=datetime.timedelta(0), max_length=1055, null=True)),
                ('marit_status', models.CharField(choices=[('QUALIFIED', 'QUALIFIED'), ('NOT-QUAILIFIED', 'NOT-QUAILIFIED')], default='NOT-QUAILIFIED', max_length=100)),
                ('corrent_anwswer', models.IntegerField(blank=True, default=0, null=True)),
                ('skipped_anwswer', models.CharField(blank=True, max_length=1055, null=True)),
                ('percantage', models.CharField(blank=True, max_length=1055, null=True)),
                ('awnsers_percantage', models.FloatField(blank=True, max_length=1055, null=True)),
                ('total_attempt_answer', models.CharField(blank=True, max_length=1055, null=True)),
                ('total_assigned_answer', models.CharField(blank=True, max_length=1055, null=True)),
                ('total_submitted_answer', models.CharField(blank=True, max_length=1055, null=True)),
                ('final_score', models.CharField(blank=True, max_length=1055, null=True)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('quizopen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizopen.quizopenmodel')),
                ('quizstart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizstart.quizstartmodel')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
