# Generated by Django 4.0.6 on 2022-12-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizresult', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresultmodel',
            name='new_status',
            field=models.CharField(choices=[('FREE', 'FREE'), ('NONFREE', 'NONFREE')], default='FREE', max_length=100),
        ),
    ]
