# Generated by Django 4.0.6 on 2022-09-26 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key_id', models.CharField(blank=True, max_length=30, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key_cookies', models.CharField(blank=True, max_length=200, null=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserLoginSession',
                'verbose_name_plural': 'UserLoginSession',
            },
        ),
        migrations.CreateModel(
            name='PlayerProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic_name', models.CharField(blank=True, max_length=1055, null=True)),
                ('nic', models.CharField(blank=True, max_length=1055, null=True)),
                ('mobile', models.CharField(blank=True, max_length=1055, null=True)),
                ('country', models.CharField(blank=True, max_length=1055, null=True)),
                ('state', models.CharField(blank=True, max_length=1055, null=True)),
                ('city', models.CharField(blank=True, max_length=1055, null=True)),
                ('address', models.CharField(blank=True, max_length=1055, null=True)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
