# Generated by Django 4.0.6 on 2022-11-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginsession',
            name='session_key_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
