# Generated by Django 4.1 on 2025-04-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authentication', '0002_alter_userloginsession_session_key_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofilemodel',
            name='category',
            field=models.CharField(blank=True, choices=[('tech', 'Technology'), ('science', 'Science'), ('arts', 'Arts'), ('business', 'Business'), ('education', 'Education')], max_length=100, null=True),
        ),
    ]
